### ISSUE TITLE
[BUG] - Update various `nhcarrigan` instances to `naomi-lgbt`

### ISSUE THREAD

**Issue by Panquesito7** [nhcommunity/handbook#11]
### What bug did you encounter?

Various texts are still using `nhcarrigan` as a way to contact Naomi, however, I believe this should be updated to `naomi-lgbt`.
The founding file is still pointing to `nhcarrigan` which is Naomi's community management firm. I believe it should point to Naomi's personal GitHub account.

### What did you expect to happen?

Already explained above.

### Additional information

This is a good first issue. Please leave it open to beginners or first-time contributors. 🙂

**Comment by naomi-lgbt** [comment]
This is actually intentional, and why our sites are still under the nhcarrigan.com domain.

We're operating this open-source community as an extension of the business (:
