### ISSUE TITLE
[BUG] - Fix moderation guide to use slash commands

### ISSUE THREAD

**Issue by Panquesito7** [nhcommunity/handbook#9]
### What bug did you encounter?

The current documentation explaining the moderation commands is outdated and it's not written using the slash commands.
There might be other instances of this in other documentation, but I only found it in the moderator guide.

### What did you expect to happen?

Instead of using the old Discord commands, we should update the documentation to match the new Discord slash commands.

### Screenshots

![image](https://user-images.githubusercontent.com/51391473/188054803-00e919bf-6c1c-4013-8836-7bd32786556f.png)

### Additional information

If possible, I'd like to work on this issue. Although, if you wanna work on it, let me know in the comments! 🙂

**Comment by naomi-lgbt** [comment]
This is a good idea. We should also document the mute process.
